[[MuesliMaterials]]
arch = "aarch64"
git-tree-sha1 = "a66f26ea40358e3fe576638f77d1a12e39b875c1"
os = "macos"

    [[MuesliMaterials.download]]
    sha256 = "5a93ee8ed9a51c41bb38f2d7f6c66dad5f1823e7b022161178568e0ebb3723bb"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.aarch64-apple-darwin.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0cc46deab953b772f25fb904d8222a26e289fac"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "b7bf31c365e1d626df41e65742fd544cb36d2e8ecac5d5c68552c3bb78341537"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.aarch64-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67af3e89b8d22c8e6afebbe9fe62524c923021e5"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "4495d32edf4cf95dd85b3bce5ae56ceae35f480a8b8ab6511c45ed8e718ac592"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.aarch64-linux-musl-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
git-tree-sha1 = "218d73e5267d734fd514450a8a12548a7a200c3a"
os = "freebsd"

    [[MuesliMaterials.download]]
    sha256 = "90c5d18b310dc6cf181b829af90411a41db40f419019bc39172b67597206aa89"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.aarch64-unknown-freebsd.tar.gz"
[[MuesliMaterials]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "688334ca69677461d284bf569ec9b03b5587d0eb"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "9320b12db16515fcc3d73b78cb8f3535ff9c46a1f31c5091dc8100240cfb2b7d"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e00b2fc812b1c21a31581966b136396570f22fd"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "a9e94335024a710d047c1329ee567636b265c994dd95db31cc151718d44b760e"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "371aabfd2566b66f866602e034d2409d9f942b91"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "6ca8ad7581f693d4317f0e77a5c903c3041145ca6cd721af871a4f7fcbe9812e"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39536cde65eecfa4fff559e38da434cda6c0b25d"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "3955865f5dbf572605be8f355724823b796d8e6221ad3448ab4c72f0d465ece9"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c94a63b502ee67cadf23d27169d33a8598c3c12f"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "11c82953a0e574517a8312c08f6e57dec0bbb3b7478d40ab200e9e584fb9bc1b"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.i686-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80b5da61b8124a67c62d5bd14e670db05d545d69"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "3238cc16ca6b654b336deebc5a29a6e70b8cd1a94c8df6c53e45330210935260"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.i686-linux-musl-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34fb53ff4a333e8c512e453e2e302e7e5ab33b36"
os = "windows"

    [[MuesliMaterials.download]]
    sha256 = "ef8ce20dc2167f57495c4bab8f5221d0ede11cc53d29805d7f93af393b3edc88"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.i686-w64-mingw32-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ab105de3ca574dd137896f6b5fd02f9f015ef8e"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "729d808f84cddb9f9a289f531405c1315d709295c4866afddd88fa7d2ca39aec"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44425e8be960d00184aa946a2f272d2165c58257"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "c7f0a5108968f57cd9b019b96ba129bd048ec778bcba3148b58c11f188528443"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.riscv64-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
git-tree-sha1 = "92fff6a9ed5291b5bcc2767fbf5cfb809055e228"
os = "macos"

    [[MuesliMaterials.download]]
    sha256 = "b7d930db798753557c02f7a1b04d0b7568dd7af1ad9802122e682a6e1d3053d8"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-apple-darwin.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93d975e7e2b5b31124119766ddc5218f9088762f"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "481cd63745376cd0e65365ad88c41fedb12ab663aa31821e21d0ea7628e10d39"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d452d577e2949f930379eafd261cc4d5bebe28d3"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "9f9bd866f608045bd5edcd566c79a3bad26d94c6b42155b2532839693eac0810"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-linux-musl-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
git-tree-sha1 = "68b831621fe70ea17f35df251e01effbfaf185af"
os = "freebsd"

    [[MuesliMaterials.download]]
    sha256 = "7d41d3f2d9a4b43d83f9acda5515abb15b6b710409881385d35dfc895f945949"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-unknown-freebsd.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c32aea6ceaa52fe8fa698d481b019679a2c8d10"
os = "windows"

    [[MuesliMaterials.download]]
    sha256 = "7ef228b13503a31138b3cb7110d7e47182d06f2168fdab596ebd419acc3aaf39"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-w64-mingw32-cxx11.tar.gz"
