[[MuesliMaterials]]
arch = "aarch64"
git-tree-sha1 = "c27adbe03915eb7f7fcf699e0377c813fda21a6f"
os = "macos"

    [[MuesliMaterials.download]]
    sha256 = "6ab5ad95bea229def71b88b2f5c6ef885563a184c815ddd94ad1f23a672ae275"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.aarch64-apple-darwin.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "282e24074f9c222867bee297ba4819819172494c"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "ce9c688a0ba50a19517ed01b161b630e5634b79c456ce5b257ea3203d7a0d71a"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b823ea0f8b378ca5473976fbf10c14f63e1a7a70"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "6de7ffc91c31269b0393ed61154a99a28b06b9e5c235ca4592fbf319a0728971"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.aarch64-linux-musl-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
git-tree-sha1 = "1841936f7043f09ea69c73e92ec7ae8792a4145d"
os = "freebsd"

    [[MuesliMaterials.download]]
    sha256 = "841949baadcd986ff838e721c00cb0b9e425a885957257d228923f5c7da4524d"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.aarch64-unknown-freebsd.tar.gz"
[[MuesliMaterials]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64732b48d384b097a0b3199d2fb190ca02d9b41e"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "6205d623a1eee72b01411a4f46f5a797998402eb383e9d287c52bee8c60c85db"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "173fb3a1ee7427e1e22128c66b87689fcd13ced2"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "f90b082df5808fb11f0a06f4e6b067dfeaa8c9277daeaf58b1d2628c720c0ef6"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f862f11b11b2a9090d33baedbfbe74962d03f8ef"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "21e88370b194d6eb81306b588c9a030dcd47010438d9e319ff57938770e39ee5"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf8da2ce1c9d93a8359b82a19a832adcb1f7b9b8"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "48300209068b675b9fa5c5d1d9ca7c7898a0c780352d2702f50281b3a1437b01"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d77528fdc0b72d1121c933feee417aef42547bb"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "28817987f6251eda28d6a0c5587850f141ca2902e94ec2ffd7bc788bcbaa05d2"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.i686-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "684d724489818285772627997cacb62edc2acd06"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "7e8195bdcfa3065f852f73ffbe96eb1e8ea9e4fa531a2001dc81de02c467dc7b"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.i686-linux-musl-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8a9f70a349a0e0dca427fe2948a79ca5a02fc07"
os = "windows"

    [[MuesliMaterials.download]]
    sha256 = "77ec3f7a633fdd03aebe5a97e0b24d0659c52bb9c24c382516b85dda781b0fe2"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.i686-w64-mingw32-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a29a979b4cdf81415b59d4d20b8071a2f39535a4"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "c63732929ea7a4d4ed6618d0d9d7903fb7e993fe334a3e76a44c1b50c8592882"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8eb02bcec0a1877e9caac019128a8b1ee9e8311"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "bb0fd2fc852d1f174b1c7d43564bde7264b1fc4d4e676255622fcd3c2069e219"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.riscv64-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
git-tree-sha1 = "7c4a0d4997550e0d3b89f891042944ea0bff7fd7"
os = "macos"

    [[MuesliMaterials.download]]
    sha256 = "0336774ad5130eeb9506e301cc4166f034b1beec4a1a7a4840205b2a306d87f1"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.x86_64-apple-darwin.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6401ac6832f09f59af611e6883581224012fd429"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "11b007ab19fd0908db515dabaca599f15641481655a65cfed01ea41f607e1106"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b48ecd70a1978189dd82de02d660bfd0205e4b6"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "52cedd859c9c715475098b5dd857e0e9513f6c36a515dcac2c94df4f3c6f6539"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.x86_64-linux-musl-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
git-tree-sha1 = "f8ff5c1256d9c256dfc5d6cfe122c96c30a84da5"
os = "freebsd"

    [[MuesliMaterials.download]]
    sha256 = "2bc98cb8ae13e1d080981d5e464690813d95c66e013073968bb481d89280b8b9"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.x86_64-unknown-freebsd.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7546ce28947b9b0c0e875a7384b70f0af77c3d59"
os = "windows"

    [[MuesliMaterials.download]]
    sha256 = "70e989009f55bb06a5e313188b2311d80865bb24dee4d17030654e5be8c667ef"
    url = "https://github.com/JuliaBinaryWrappers/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.1+0/MuesliMaterials.v1.16.1.x86_64-w64-mingw32-cxx11.tar.gz"
